# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the rest of the code
COPY . .

# Build the project
RUN npm run build

EXPOSE 3000

# Set environment variable placeholder (user should override these values in production)
ENV YNAB_API_TOKEN=""
# optional:
# ENV YNAB_BUDGET_ID=""

# Streamable HTTP endpoint at /mcp; pass no args (or override CMD) for stdio mode
CMD ["node", "dist/index.js", "--transport", "http", "--host", "0.0.0.0", "--port", "3000"]
